version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres-fullstack-assessment
    ports:
      - 8432:5432
    volumes:
      - ./postgres/:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=library_db
      - POSTGRES_PASSWORD=postgres
      - PUID=1000
      - PGID=1000
